Milestone-2: Mobile First Portfolio pull request
HussenYesufAlli/Hussen-Yesuf-Portfolio pull request #1
Opened 2023-04-26 18:39 UTC by HussenYesufAlli

In this milestone, I: 
Use the HTML&CSS linter configuration 
Add header/Top bar section
Add Headline section

2023-04-26 19:36 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @HussenYesufAlli, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GiHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 19:36 UTC, Qoosim commented on index.html
> +      </div>
- [ ] It is required that the hamburger should be wrapped in a `nav` tag. Kindly change the ordinary `div` to `nav` tag. The nav tag is for semantics reason, and the right position for convention and user experience for mobile devices.

2023-04-26 19:36 UTC, Qoosim commented on index.html
> +                <img src="img/t.png" alt="tiwetter" />
- [ ] Kindly reduce the font-size of this social media icon. It's kind of bigger than others.

### Your Design
![your-design](https://user-images.githubusercontent.com/26597432/234683508-a397cef3-5208-4de6-8637-a6c6b0b4ddba.png)

### Figma Design
![temp-design](https://user-images.githubusercontent.com/26597432/234683546-ed7612cf-f2c8-4c0b-a181-660a191439e9.png)

2023-04-27 04:11 UTC, AdnanOlarmmi approved these changes
Hi @HussenYesufAlli ,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- fixed previous reviewer suggestion.
- Nice UI

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 09:04 UTC, merged